### ISSUE TITLE
UnboundLocalError: local variable 'window' referenced before assignment

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/TabsExtra#43]
### UnboundLocalError: local variable 'window' referenced before assignment

I found this on my console, after open Sublime Text and some other projects. Yet I do not know how to reproduce.
```
Traceback (most recent call last):
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\sublime_plugin.py", line 452, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "tabs_extra in D:\User\Dropbox\Applications\SoftwareVersioning\SublimeText\Data\Installed Packages\TabsExtra.sublime-package", line 706, in on_close
UnboundLocalError: local variable 'window' referenced before assignment
```

**Comment by facelessuser** [comment]
Thanks!  Just needed to initialize the variable to None in case we didn't find a the window we were looking for.  Not sure what path got us there...but the immediate problem is resolved.
