### ISSUE TITLE
UnboundLocalError: local variable 'window' referenced before assignment

### ISSUE THREAD

**Issue by evandrocoan** [facelessuser/TabsExtra#47]
I just looked into the console and I found several of these:

```
Traceback (most recent call last):
  File "D:\SublimeText\sublime_plugin.py", line 389, in run_callback
    expr()
  File "D:\SublimeText\sublime_plugin.py", line 452, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "tabs_extra in D:\SublimeText\Data\Installed Packages\TabsExtra.sublime-package", line 706, in on_close
UnboundLocalError: local variable 'window' referenced before assignment
```

``` 
- ST ver.:        3131
- Platform:       windows
- Arch:           x32
- Plugin ver.:    1.3.0
- Install via PC: True
```

**Comment by facelessuser** [comment]
Thanks.  I'll take a look sometime soon.

**Comment by facelessuser** [comment]
This was actually fixed a while ago: https://github.com/facelessuser/TabsExtra/commit/d98f37c2c6241f53b599a81a6701989dafa282da.  I just never remembered to to release it.

**Comment by facelessuser** [comment]
This has **actually** been released now.

**Comment by evandrocoan** [comment]
Thanks.
